create table if not exists public.moment_candidates (
  id bigint generated by default as identity primary key,
  user_id text not null,
  text text not null,
  image_key text,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'published', 'skipped', 'failed')),
  priority smallint not null default 1
    check (priority between 1 and 3),
  publish_after timestamptz not null,
  expires_at timestamptz not null,
  source_conversation_id text,
  source_message_id text,
  published_moment_id text,
  skip_reason text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, source_message_id)
);

create index if not exists moment_candidates_pending_idx
  on public.moment_candidates (status, publish_after, priority desc)
  where status = 'pending';
