create table if not exists public.album_assets (
  id bigint generated by default as identity primary key,
  user_id text not null,
  storage_path text not null,
  mime_type text not null default 'image/jpeg',
  aspect_ratio double precision,
  description text not null default '',
  categories text[] not null default '{}',
  time_periods text[] not null default '{}',
  weather text,
  access_scope text not null default 'shared'
    check (access_scope in ('shared', 'private')),
  enabled boolean not null default true,
  usage_count integer not null default 0,
  last_used_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists album_assets_available_idx
  on public.album_assets (user_id, access_scope, enabled, last_used_at, created_at desc)
  where archived_at is null;
