create table if not exists public.moment_xiaoc_activity (
  id bigint generated by default as identity primary key,
  user_id text not null,
  moment_id text not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'seen', 'completed', 'skipped', 'failed')),
  source_version integer not null default 1,
  next_check_at timestamptz not null,
  seen_at timestamptz,
  decision text,
  liked_at timestamptz,
  comment_id text,
  decision_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, moment_id, source_version)
);

create index if not exists moment_xiaoc_activity_pending_idx
  on public.moment_xiaoc_activity (status, next_check_at)
  where status = 'pending';
