create table if not exists public.moment_xiaoc_activity (
  id bigint generated by default as identity primary key,
  user_id text not null,
  moment_id text not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'seen', 'completed', 'skipped', 'failed')),
  source_version integer not null default 1,
  next_check_at timestamptz not null,
  seen_at timestamptz,
  decision text,
  liked_at timestamptz,
  comment_id text,
  decision_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, moment_id, source_version)
);

create index if not exists moment_xiaoc_activity_pending_idx
  on public.moment_xiaoc_activity (status, next_check_at)
  where status = 'pending';

create extension if not exists pg_cron with schema extensions;
create extension if not exists pg_net with schema extensions;

do $$
declare
  existing_job_id bigint;
begin
  for existing_job_id in
    select jobid
    from cron.job
    where jobname in (
      'xiaoc-moment-seen-check',
      'xiaoc-moment-interaction-worker',
      'xiaoc-background-worker'
    )
  loop
    perform cron.unschedule(existing_job_id);
  end loop;

  perform cron.schedule(
    'xiaoc-moment-interaction-worker',
    '* * * * *',
    $schedule$
      select net.http_get(
        url := (
          select decrypted_secret
          from vault.decrypted_secrets
          where name = 'xiaoc_api_base_url'
          limit 1
        ) || '/api/memory?type=moment_interaction_check',
        headers := jsonb_build_object(
          'Authorization',
          'Bearer ' || (
            select decrypted_secret
            from vault.decrypted_secrets
            where name = 'xiaoc_cron_secret'
            limit 1
          )
        ),
        timeout_milliseconds := 30000
      );
    $schedule$
  );

  perform cron.schedule(
    'xiaoc-background-worker',
    '0 * * * *',
    $schedule$
      select net.http_get(
        url := (
          select decrypted_secret
          from vault.decrypted_secrets
          where name = 'xiaoc_api_base_url'
          limit 1
        ) || '/api/memory?type=xiaoc_background_check',
        headers := jsonb_build_object(
          'Authorization',
          'Bearer ' || (
            select decrypted_secret
            from vault.decrypted_secrets
            where name = 'xiaoc_cron_secret'
            limit 1
          )
        ),
        timeout_milliseconds := 30000
      );
    $schedule$
  );
end;
$$;
