-- Additive, privacy-safe XiaoC Memory observation audit.
create table if not exists public.xiaoc_memory_observation_audit (
  id bigint generated by default as identity primary key,
  user_id text not null check (btrim(user_id) <> ''),
  occurred_at timestamptz not null,
  event_kind text not null check (event_kind in ('retrieval_shadow', 'native_capture_shadow')),
  environment text not null check (char_length(environment) between 1 and 32),
  deployment_id text check (deployment_id is null or char_length(deployment_id) between 1 and 128),
  policy_version text not null check (char_length(policy_version) between 1 and 80),
  correlation_id_hash text not null check (correlation_id_hash ~ '^[0-9a-f]{64}$'),
  retrieval_mode text check (retrieval_mode is null or retrieval_mode in ('normal_current', 'historical_recall')),
  eligible_opportunity boolean not null default false,
  sampled boolean not null default false,
  attempted boolean not null default false,
  outcome text not null check (outcome in ('skipped', 'success', 'empty', 'failure', 'timeout', 'duplicate')),
  reason_code text check (reason_code is null or char_length(reason_code) between 1 and 80),
  error_code text check (error_code is null or char_length(error_code) between 1 and 80),
  candidate_count integer not null default 0 check (candidate_count between 0 and 10000),
  eligible_count integer not null default 0 check (eligible_count between 0 and 10000),
  selected_count integer not null default 0 check (selected_count between 0 and 10000),
  selected_origin_counts jsonb not null default '{}'::jsonb check (jsonb_typeof(selected_origin_counts) = 'object' and octet_length(selected_origin_counts::text) <= 2048),
  authority_counts jsonb not null default '{}'::jsonb check (jsonb_typeof(authority_counts) = 'object' and octet_length(authority_counts::text) <= 2048),
  tier_counts jsonb not null default '{}'::jsonb check (jsonb_typeof(tier_counts) = 'object' and octet_length(tier_counts::text) <= 2048),
  ombre_count integer check (ombre_count is null or ombre_count between 0 and 10000),
  overlap_count integer check (overlap_count is null or overlap_count between 0 and 10000),
  total_latency_ms integer check (total_latency_ms is null or total_latency_ms between 0 and 300000),
  stage_latency_ms jsonb not null default '{}'::jsonb check (jsonb_typeof(stage_latency_ms) = 'object' and octet_length(stage_latency_ms::text) <= 2048),
  created_at timestamptz not null default now(),
  check (selected_count <= eligible_count or event_kind = 'native_capture_shadow'),
  check (eligible_count <= candidate_count or event_kind = 'native_capture_shadow'),
  check (not attempted or sampled),
  check (event_kind <> 'native_capture_shadow' or retrieval_mode is null)
);

create index if not exists xiaoc_memory_observation_audit_user_occurred_idx
  on public.xiaoc_memory_observation_audit (user_id, occurred_at desc);
create index if not exists xiaoc_memory_observation_audit_kind_occurred_idx
  on public.xiaoc_memory_observation_audit (event_kind, occurred_at desc);
create index if not exists xiaoc_memory_observation_audit_outcome_occurred_idx
  on public.xiaoc_memory_observation_audit (outcome, occurred_at desc);
create index if not exists xiaoc_memory_observation_audit_created_idx
  on public.xiaoc_memory_observation_audit (created_at);

alter table public.xiaoc_memory_observation_audit enable row level security;

revoke all on public.xiaoc_memory_observation_audit from public, anon, authenticated;
revoke all on sequence public.xiaoc_memory_observation_audit_id_seq from public, anon, authenticated;
revoke update, delete, truncate, references, trigger on public.xiaoc_memory_observation_audit from service_role;
grant select, insert on public.xiaoc_memory_observation_audit to service_role;
grant usage, select on sequence public.xiaoc_memory_observation_audit_id_seq to service_role;

create or replace function public.cleanup_xiaoc_observability_audits(
  p_retention_days integer default 60
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if p_retention_days < 30 or p_retention_days > 365 then
    raise exception 'invalid retention days';
  end if;
  delete from public.treehole_execution_audit
  where created_at < now() - make_interval(days => p_retention_days);
  delete from public.background_worker_run_audit
  where created_at < now() - make_interval(days => p_retention_days);
  delete from public.xiaoc_memory_observation_audit
  where created_at < now() - make_interval(days => p_retention_days);
end;
$$;

revoke all on function public.cleanup_xiaoc_observability_audits(integer) from public, anon, authenticated;
grant execute on function public.cleanup_xiaoc_observability_audits(integer) to service_role;
