create table if not exists public.treehole_execution_audit (
  id bigint generated by default as identity primary key,
  user_id text not null,
  task_id bigint not null,
  scheduled_for timestamptz not null,
  started_at timestamptz not null,
  finished_at timestamptz not null,
  new_user_message_count integer not null default 0 check (new_user_message_count >= 0),
  new_user_char_count integer not null default 0 check (new_user_char_count >= 0),
  prefilter_result text not null,
  judge_attempted boolean not null default false,
  judge_result text not null,
  publish_attempted boolean not null default false,
  publish_result text not null,
  reason_code text not null check (reason_code in (
    'cooldown', 'insufficient_new_messages', 'insufficient_new_chars',
    'judge_declined', 'judge_invalid_output', 'publish_success',
    'publish_failed', 'task_rescheduled', 'exception'
  )),
  error_code text,
  next_scheduled_for timestamptz,
  duration_ms integer not null default 0 check (duration_ms >= 0),
  created_at timestamptz not null default now()
);

create index if not exists treehole_execution_audit_user_started_idx
  on public.treehole_execution_audit (user_id, started_at desc);
create index if not exists treehole_execution_audit_created_idx
  on public.treehole_execution_audit (created_at);

alter table public.treehole_execution_audit enable row level security;

create table if not exists public.background_worker_run_audit (
  id bigint generated by default as identity primary key,
  user_id text not null,
  worker_type text not null check (worker_type = 'xiaoc_background_check'),
  started_at timestamptz not null,
  finished_at timestamptz not null,
  tasks_due integer not null default 0 check (tasks_due >= 0),
  tasks_processed integer not null default 0 check (tasks_processed >= 0),
  tasks_succeeded integer not null default 0 check (tasks_succeeded >= 0),
  tasks_skipped integer not null default 0 check (tasks_skipped >= 0),
  tasks_failed integer not null default 0 check (tasks_failed >= 0),
  treehole_tasks_processed integer not null default 0 check (treehole_tasks_processed >= 0),
  proactive_tasks_processed integer not null default 0 check (proactive_tasks_processed >= 0),
  duration_ms integer not null default 0 check (duration_ms >= 0),
  result text not null check (result in (
    'SUCCESS_NO_DUE_TASKS', 'SUCCESS_PROCESSED', 'PARTIAL_FAILURE', 'FAILED'
  )),
  error_code text,
  created_at timestamptz not null default now()
);

create index if not exists background_worker_run_audit_started_idx
  on public.background_worker_run_audit (user_id, worker_type, started_at desc);
create index if not exists background_worker_run_audit_created_idx
  on public.background_worker_run_audit (created_at);

alter table public.background_worker_run_audit enable row level security;

revoke insert, update, delete, truncate on public.treehole_execution_audit from public, anon, authenticated;
revoke insert, update, delete, truncate on public.background_worker_run_audit from public, anon, authenticated;
grant select on public.treehole_execution_audit to service_role;
grant select on public.background_worker_run_audit to service_role;
grant insert on public.treehole_execution_audit to service_role;
grant insert on public.background_worker_run_audit to service_role;
grant usage, select on sequence public.treehole_execution_audit_id_seq to service_role;
grant usage, select on sequence public.background_worker_run_audit_id_seq to service_role;

create or replace function public.cleanup_xiaoc_observability_audits(
  p_retention_days integer default 60
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_retention_days < 30 or p_retention_days > 365 then
    raise exception 'invalid retention days';
  end if;
  delete from public.treehole_execution_audit
  where created_at < now() - make_interval(days => p_retention_days);
  delete from public.background_worker_run_audit
  where created_at < now() - make_interval(days => p_retention_days);
end;
$$;

revoke all on function public.cleanup_xiaoc_observability_audits(integer) from public, anon, authenticated;
grant execute on function public.cleanup_xiaoc_observability_audits(integer) to service_role;
