create table if not exists public.moment_check_audit (
  id bigint generated by default as identity primary key,
  user_id text not null,
  conversation_id text not null,
  source_user_message_id text,
  source_assistant_message_id text,
  trigger_type text not null
    check (trigger_type in ('auto', 'manual')),
  status text not null default 'started'
    check (status in ('started', 'completed', 'failed')),
  eligibility_result boolean,
  skip_reason text,
  model_called boolean not null default false,
  model_should_post boolean,
  requested_image_id text,
  image_validation_result text
    check (
      image_validation_result is null or
      image_validation_result in ('not_requested', 'accepted', 'rejected')
    ),
  image_resolution_result text
    check (
      image_resolution_result is null or
      image_resolution_result in ('not_applicable', 'resolved', 'failed')
    ),
  resolved_image_key text,
  candidate_id bigint references public.moment_candidates(id) on delete set null,
  outcome text,
  error_code text,
  checked_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (user_id, source_assistant_message_id, trigger_type)
);

create index if not exists moment_check_audit_gate_idx
  on public.moment_check_audit (
    user_id,
    conversation_id,
    trigger_type,
    checked_at desc
  );

create index if not exists moment_check_audit_outcome_idx
  on public.moment_check_audit (outcome, checked_at desc);

create or replace function public.claim_moment_check(
  p_user_id text,
  p_conversation_id text,
  p_source_user_message_id text,
  p_source_assistant_message_id text,
  p_min_interval_minutes integer default 30
)
returns table (
  claimed boolean,
  audit_id bigint,
  reason text,
  last_checked_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  latest_check public.moment_check_audit%rowtype;
  new_audit_id bigint;
begin
  if p_user_id is null or btrim(p_user_id) = '' or
     p_conversation_id is null or btrim(p_conversation_id) = '' or
     p_source_user_message_id is null or btrim(p_source_user_message_id) = '' or
     p_source_assistant_message_id is null or btrim(p_source_assistant_message_id) = '' then
    return query select false, null::bigint, 'missing_source_message'::text, null::timestamptz;
    return;
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_user_id || chr(31) || p_conversation_id, 0)
  );

  if not exists (
    select 1
    from public.conversations c
    where c.user_id = p_user_id
      and c.conversation_id = p_conversation_id
  ) then
    return query select false, null::bigint, 'conversation_missing'::text, null::timestamptz;
    return;
  end if;

  select a.*
  into latest_check
  from public.moment_check_audit a
  where a.user_id = p_user_id
    and a.conversation_id = p_conversation_id
    and a.trigger_type = 'auto'
  order by a.checked_at desc
  limit 1;

  if latest_check.id is not null and
     latest_check.source_user_message_id = p_source_user_message_id then
    return query select false, null::bigint, 'no_new_user_message'::text, latest_check.checked_at;
    return;
  end if;

  if latest_check.id is not null and
     latest_check.checked_at > now() - make_interval(mins => greatest(p_min_interval_minutes, 1)) then
    return query select false, null::bigint, 'interval_not_reached'::text, latest_check.checked_at;
    return;
  end if;

  insert into public.moment_check_audit (
    user_id,
    conversation_id,
    source_user_message_id,
    source_assistant_message_id,
    trigger_type
  ) values (
    p_user_id,
    p_conversation_id,
    p_source_user_message_id,
    p_source_assistant_message_id,
    'auto'
  )
  returning id into new_audit_id;

  return query select true, new_audit_id, 'claimed'::text, latest_check.checked_at;
end;
$$;

revoke all on function public.claim_moment_check(
  text,
  text,
  text,
  text,
  integer
) from public, anon, authenticated;

grant execute on function public.claim_moment_check(
  text,
  text,
  text,
  text,
  integer
) to service_role;
